/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TExplainLevel implements org.apache.thrift.TEnum {
  NORMAL(0),
  VERBOSE(1),
  COSTS(2);

  private final int value;

  private TExplainLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TExplainLevel findByValue(int value) { 
    switch (value) {
      case 0:
        return NORMAL;
      case 1:
        return VERBOSE;
      case 2:
        return COSTS;
      default:
        return null;
    }
  }
}
