/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;


public enum TFunctionType implements org.apache.thrift.TEnum {
  SCALAR(0),
  AGGREGATE(1);

  private final int value;

  private TFunctionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TFunctionType findByValue(int value) { 
    switch (value) {
      case 0:
        return SCALAR;
      case 1:
        return AGGREGATE;
      default:
        return null;
    }
  }
}
