/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TLoadType implements org.apache.thrift.TEnum {
  MANUAL_LOAD(0),
  ROUTINE_LOAD(1),
  MINI_LOAD(2);

  private final int value;

  private TLoadType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TLoadType findByValue(int value) { 
    switch (value) {
      case 0:
        return MANUAL_LOAD;
      case 1:
        return ROUTINE_LOAD;
      case 2:
        return MINI_LOAD;
      default:
        return null;
    }
  }
}
