/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TTableFunction implements org.apache.thrift.TBase<TTableFunction, TTableFunction._Fields>, java.io.Serializable, Cloneable, Comparable<TTableFunction> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTableFunction");

  private static final org.apache.thrift.protocol.TField RET_TYPES_FIELD_DESC = new org.apache.thrift.protocol.TField("ret_types", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TTableFunctionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TTableFunctionTupleSchemeFactory());
  }

  public List<TTypeDesc> ret_types; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RET_TYPES((short)1, "ret_types");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RET_TYPES
          return RET_TYPES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RET_TYPES, new org.apache.thrift.meta_data.FieldMetaData("ret_types", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TTypeDesc.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTableFunction.class, metaDataMap);
  }

  public TTableFunction() {
  }

  public TTableFunction(
    List<TTypeDesc> ret_types)
  {
    this();
    this.ret_types = ret_types;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TTableFunction(TTableFunction other) {
    if (other.isSetRet_types()) {
      List<TTypeDesc> __this__ret_types = new ArrayList<TTypeDesc>(other.ret_types.size());
      for (TTypeDesc other_element : other.ret_types) {
        __this__ret_types.add(new TTypeDesc(other_element));
      }
      this.ret_types = __this__ret_types;
    }
  }

  public TTableFunction deepCopy() {
    return new TTableFunction(this);
  }

  @Override
  public void clear() {
    this.ret_types = null;
  }

  public int getRet_typesSize() {
    return (this.ret_types == null) ? 0 : this.ret_types.size();
  }

  public java.util.Iterator<TTypeDesc> getRet_typesIterator() {
    return (this.ret_types == null) ? null : this.ret_types.iterator();
  }

  public void addToRet_types(TTypeDesc elem) {
    if (this.ret_types == null) {
      this.ret_types = new ArrayList<TTypeDesc>();
    }
    this.ret_types.add(elem);
  }

  public List<TTypeDesc> getRet_types() {
    return this.ret_types;
  }

  public TTableFunction setRet_types(List<TTypeDesc> ret_types) {
    this.ret_types = ret_types;
    return this;
  }

  public void unsetRet_types() {
    this.ret_types = null;
  }

  /** Returns true if field ret_types is set (has been assigned a value) and false otherwise */
  public boolean isSetRet_types() {
    return this.ret_types != null;
  }

  public void setRet_typesIsSet(boolean value) {
    if (!value) {
      this.ret_types = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RET_TYPES:
      if (value == null) {
        unsetRet_types();
      } else {
        setRet_types((List<TTypeDesc>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RET_TYPES:
      return getRet_types();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RET_TYPES:
      return isSetRet_types();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TTableFunction)
      return this.equals((TTableFunction)that);
    return false;
  }

  public boolean equals(TTableFunction that) {
    if (that == null)
      return false;

    boolean this_present_ret_types = true && this.isSetRet_types();
    boolean that_present_ret_types = true && that.isSetRet_types();
    if (this_present_ret_types || that_present_ret_types) {
      if (!(this_present_ret_types && that_present_ret_types))
        return false;
      if (!this.ret_types.equals(that.ret_types))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TTableFunction other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRet_types()).compareTo(other.isSetRet_types());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRet_types()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ret_types, other.ret_types);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TTableFunction(");
    boolean first = true;

    sb.append("ret_types:");
    if (this.ret_types == null) {
      sb.append("null");
    } else {
      sb.append(this.ret_types);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (ret_types == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ret_types' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TTableFunctionStandardSchemeFactory implements SchemeFactory {
    public TTableFunctionStandardScheme getScheme() {
      return new TTableFunctionStandardScheme();
    }
  }

  private static class TTableFunctionStandardScheme extends StandardScheme<TTableFunction> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TTableFunction struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RET_TYPES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.ret_types = new ArrayList<TTypeDesc>(_list16.size);
                for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                {
                  TTypeDesc _elem18;
                  _elem18 = new TTypeDesc();
                  _elem18.read(iprot);
                  struct.ret_types.add(_elem18);
                }
                iprot.readListEnd();
              }
              struct.setRet_typesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TTableFunction struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ret_types != null) {
        oprot.writeFieldBegin(RET_TYPES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ret_types.size()));
          for (TTypeDesc _iter19 : struct.ret_types)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TTableFunctionTupleSchemeFactory implements SchemeFactory {
    public TTableFunctionTupleScheme getScheme() {
      return new TTableFunctionTupleScheme();
    }
  }

  private static class TTableFunctionTupleScheme extends TupleScheme<TTableFunction> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TTableFunction struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.ret_types.size());
        for (TTypeDesc _iter20 : struct.ret_types)
        {
          _iter20.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TTableFunction struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.ret_types = new ArrayList<TTypeDesc>(_list21.size);
        for (int _i22 = 0; _i22 < _list21.size; ++_i22)
        {
          TTypeDesc _elem23;
          _elem23 = new TTypeDesc();
          _elem23.read(iprot);
          struct.ret_types.add(_elem23);
        }
      }
      struct.setRet_typesIsSet(true);
    }
  }

}

