/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;


public enum TVarType implements org.apache.thrift.TEnum {
  SESSION(0),
  GLOBAL(1);

  private final int value;

  private TVarType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TVarType findByValue(int value) { 
    switch (value) {
      case 0:
        return SESSION;
      case 1:
        return GLOBAL;
      default:
        return null;
    }
  }
}
