/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.flink.thrift;

public class TypesConstants {

  public static final int TSNAPSHOT_REQ_VERSION1 = 3;

  public static final int TSNAPSHOT_REQ_VERSION2 = 4;

  public static final int TPREFER_SNAPSHOT_REQ_VERSION = 4;

}
